/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrendsRouteImport } from './routes/app.trends'
import { Route as AppSocialRouteImport } from './routes/app.social'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSeoRouteImport } from './routes/app.seo'
import { Route as AppScriptsRouteImport } from './routes/app.scripts'
import { Route as AppPublisherRouteImport } from './routes/app.publisher'
import { Route as AppGeneratorRouteImport } from './routes/app.generator'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppBoosterRouteImport } from './routes/app.booster'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiTrendsRouteImport } from './routes/api/trends'
import { Route as ApiIdeasRouteImport } from './routes/api/ideas'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoRoute = AppSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AppRoute,
} as any)
const AppScriptsRoute = AppScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AppRoute,
} as any)
const AppPublisherRoute = AppPublisherRouteImport.update({
  id: '/publisher',
  path: '/publisher',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorRoute = AppGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppBoosterRoute = AppBoosterRouteImport.update({
  id: '/booster',
  path: '/booster',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrendsRoute = ApiTrendsRouteImport.update({
  id: '/api/trends',
  path: '/api/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdeasRoute = ApiIdeasRouteImport.update({
  id: '/api/ideas',
  path: '/api/ideas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/ideas': typeof ApiIdeasRoute
  '/api/trends': typeof ApiTrendsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/booster': typeof AppBoosterRoute
  '/app/clients': typeof AppClientsRoute
  '/app/generator': typeof AppGeneratorRoute
  '/app/publisher': typeof AppPublisherRoute
  '/app/scripts': typeof AppScriptsRoute
  '/app/seo': typeof AppSeoRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/ideas': typeof ApiIdeasRoute
  '/api/trends': typeof ApiTrendsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/booster': typeof AppBoosterRoute
  '/app/clients': typeof AppClientsRoute
  '/app/generator': typeof AppGeneratorRoute
  '/app/publisher': typeof AppPublisherRoute
  '/app/scripts': typeof AppScriptsRoute
  '/app/seo': typeof AppSeoRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/trends': typeof AppTrendsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/ideas': typeof ApiIdeasRoute
  '/api/trends': typeof ApiTrendsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/booster': typeof AppBoosterRoute
  '/app/clients': typeof AppClientsRoute
  '/app/generator': typeof AppGeneratorRoute
  '/app/publisher': typeof AppPublisherRoute
  '/app/scripts': typeof AppScriptsRoute
  '/app/seo': typeof AppSeoRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/api/ideas'
    | '/api/trends'
    | '/app/analytics'
    | '/app/booster'
    | '/app/clients'
    | '/app/generator'
    | '/app/publisher'
    | '/app/scripts'
    | '/app/seo'
    | '/app/settings'
    | '/app/social'
    | '/app/trends'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/api/ideas'
    | '/api/trends'
    | '/app/analytics'
    | '/app/booster'
    | '/app/clients'
    | '/app/generator'
    | '/app/publisher'
    | '/app/scripts'
    | '/app/seo'
    | '/app/settings'
    | '/app/social'
    | '/app/trends'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/api/ideas'
    | '/api/trends'
    | '/app/analytics'
    | '/app/booster'
    | '/app/clients'
    | '/app/generator'
    | '/app/publisher'
    | '/app/scripts'
    | '/app/seo'
    | '/app/settings'
    | '/app/social'
    | '/app/trends'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiIdeasRoute: typeof ApiIdeasRoute
  ApiTrendsRoute: typeof ApiTrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trends': {
      id: '/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/social': {
      id: '/app/social'
      path: '/social'
      fullPath: '/app/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seo': {
      id: '/app/seo'
      path: '/seo'
      fullPath: '/app/seo'
      preLoaderRoute: typeof AppSeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scripts': {
      id: '/app/scripts'
      path: '/scripts'
      fullPath: '/app/scripts'
      preLoaderRoute: typeof AppScriptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publisher': {
      id: '/app/publisher'
      path: '/publisher'
      fullPath: '/app/publisher'
      preLoaderRoute: typeof AppPublisherRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/generator': {
      id: '/app/generator'
      path: '/generator'
      fullPath: '/app/generator'
      preLoaderRoute: typeof AppGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/booster': {
      id: '/app/booster'
      path: '/booster'
      fullPath: '/app/booster'
      preLoaderRoute: typeof AppBoosterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trends': {
      id: '/api/trends'
      path: '/api/trends'
      fullPath: '/api/trends'
      preLoaderRoute: typeof ApiTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ideas': {
      id: '/api/ideas'
      path: '/api/ideas'
      fullPath: '/api/ideas'
      preLoaderRoute: typeof ApiIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBoosterRoute: typeof AppBoosterRoute
  AppClientsRoute: typeof AppClientsRoute
  AppGeneratorRoute: typeof AppGeneratorRoute
  AppPublisherRoute: typeof AppPublisherRoute
  AppScriptsRoute: typeof AppScriptsRoute
  AppSeoRoute: typeof AppSeoRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBoosterRoute: AppBoosterRoute,
  AppClientsRoute: AppClientsRoute,
  AppGeneratorRoute: AppGeneratorRoute,
  AppPublisherRoute: AppPublisherRoute,
  AppScriptsRoute: AppScriptsRoute,
  AppSeoRoute: AppSeoRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiIdeasRoute: ApiIdeasRoute,
  ApiTrendsRoute: ApiTrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
