/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrendsRouteImport } from './routes/api/trends'
import { Route as ApiIdeasRouteImport } from './routes/api/ideas'
import { Route as ApiGenerateScriptRouteImport } from './routes/api/generate-script'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendsRoute = ApiTrendsRouteImport.update({
  id: '/api/trends',
  path: '/api/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdeasRoute = ApiIdeasRouteImport.update({
  id: '/api/ideas',
  path: '/api/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateScriptRoute = ApiGenerateScriptRouteImport.update({
  id: '/api/generate-script',
  path: '/api/generate-script',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/ideas': typeof ApiIdeasRoute
  '/api/trends': typeof ApiTrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/ideas': typeof ApiIdeasRoute
  '/api/trends': typeof ApiTrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/ideas': typeof ApiIdeasRoute
  '/api/trends': typeof ApiTrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate-script' | '/api/ideas' | '/api/trends'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-script' | '/api/ideas' | '/api/trends'
  id: '__root__' | '/' | '/api/generate-script' | '/api/ideas' | '/api/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateScriptRoute: typeof ApiGenerateScriptRoute
  ApiIdeasRoute: typeof ApiIdeasRoute
  ApiTrendsRoute: typeof ApiTrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trends': {
      id: '/api/trends'
      path: '/api/trends'
      fullPath: '/api/trends'
      preLoaderRoute: typeof ApiTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ideas': {
      id: '/api/ideas'
      path: '/api/ideas'
      fullPath: '/api/ideas'
      preLoaderRoute: typeof ApiIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-script': {
      id: '/api/generate-script'
      path: '/api/generate-script'
      fullPath: '/api/generate-script'
      preLoaderRoute: typeof ApiGenerateScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateScriptRoute: ApiGenerateScriptRoute,
  ApiIdeasRoute: ApiIdeasRoute,
  ApiTrendsRoute: ApiTrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
