// This file is automatically generated. Do not edit it directly.
// Server-side middleware is disabled in SPA mode.
// Auth is handled client-side via AuthProvider in __root.tsx.
export const requireSupabaseAuth = {};
